name: staging
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    

jobs:

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - name: Build
        run: flutter build apk --release

      - name: Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: release
          releaseNotes: "${{ github.event.head_commit.message }}"
          file: build/app/outputs/flutter-apk/app-release.apk
